version: '3.6'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: hasura
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v2.1.0-beta.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://user1:pass1@db:5432/hasura
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://user1:pass1@db:5432/hasura
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "RS256", "jwk_url":
        "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
        "audience": "<firebase-project>", "issuer":
        "https://securetoken.google.com/<firebase-project>" }'
